getContent = function () {
  return [
    {
      title:"Western Dragon",
      type: "internal_link",
      summary:"An origami dragon of high intermediate complexity. All fold angles are multiples of 22.5 degrees and relatively few folds are more than 2-ply. This makes it easier to retain accuracy and fold from a small square. The long limbs also make a variety of poses possible.",
      tags: ['origami', 'dragon', 'tutorial'],
      img:"img/dragon_CP.svg",
      link:"https://caseyshields.github.io/dragon/"
      // TODO add a list of dates to each entry...
    }, {
    //   title:"Light Tank",
    //   type: "internal_link",
    //   summary:"A lego mech which transforms into a light wheeled tank based on the Japanese MCV Type 16. Working gun and mortars are usable in both robot and vehicle mode. Originally released on the old brick link MOC pages.",
    //   tags: ['lego', 'transformer', 'tank'],
    //   img:"tank/tank.png",
    //   link:"tank/index.html"
    // }, {
    //   title:"Right Angle Fractal",
    //   type: "internal_link",
    //   summary:"Nested semi-circles inscribed with right angles. SVG generated by short Js program.",
    //   tags: ['fractal', 'origami', 'svg'],
    //   img:"rightangle/rightangle.svg",
    //   link:"rightangle/index.html"
    // }, {
    //   title:"Beam Trooper",
    //   type: "internal_link",
    //   summary:"Mobile Frame Zero is a miniatures war game where you use your legos to build terrain, robots, weapons and inventory. This mobile frame has a beam rifle and jet pack.",
    //   tags:['lego', 'MFZ', 'games'],
    //   img:"img/beamtrooper.png",
    //   link: "https://www.bricklink.com/v3/studio/design.page?idModel=44830"
    // },{
      title: "Trie Example",
      type: "internal_link",
      summary: "Demonstrates the construction of a trie data structure. The unique thing about tries is you can put millions of words in them and the retrieval time is only proportional to the length of the word. Think of a bunch of words that have the same first letter or prefixes to so how this can be. See the red dots? that's where you would link the data associated with the key.",
      tags: ['D3', 'trie', 'algorithms'],
      img: "img/trie.svg",
      link: "https://caseyshields.github.io/trie/"
    },{
    //   title: "Henderson Gallery",
    //   type: "internal_link",
    //   summary: "Part of the submission process for the gallery in Henderson's city hall is an artist statement. I've been thinking about some of this stuff for awhile and I think I summed up my thoughts okay. But is it pretentious enough? I really need to distract from my terrible photography.",
    //   tags: ['origami', 'essay', 'art'],
    //   img: "cityhall/hallDualFrames.JPG",
    //   link: "cityhall/index.html"
    // },{
      title: "Ladder Diagrams",
      type: "internal_link",
      summary: "Ladder diagrams have a discrete axis of actors, and continuous axis for time. They are used to show messaging over time in networks and computer systems.",
      tags: ['D3', 'ladder', 'component'],
      img: "img/ladder.svg",
      link: "https://caseyshields.github.io/ladder/"
    },{
      title: "Star Catalog",
      type: "internal_link",
      summary: "Playing around with projections in D3 using the FK6 star catalog.",
      tags: ['D3', 'astronomy', 'FK6', 'code', 'component'],
      img: "img/stars.png",
      link: "https://caseyshields.github.io/starmap/"
    },{
    //   title: "Rocket Swordsman",
    //   type: "internal_link",
    //   summary: "Made another figurine for MF0. Rocket propelled swordsman.",
    //   tags: ['MFZ','lego','mech'],
    //   img: "img/rocketswordsman.png",
    //   link: "https://www.bricklink.com/v3/studio/design.page?idModel=48368"
      
    // }, {
      title: "Polar Plot",
      type: "internal_link",
      summary: "Quick demo of a simple polar plot component. Exercises some mouse limited interactivity and gives some css styling ideas.",
      tags: ['D3', 'component', 'code'],
      img: "img/polar.svg",
      link: "https://caseyshields.github.io/polar/"
    }, {
      title: "Nevada",
      type: "internal_link",
      summary: "Made a layered vector map component with D3.",
      tags: ['D3', 'code', 'component'],
      img: 'img/nevada.svg',
      link: "https://caseyshields.github.io/nevada/"
    }, {
    //   title: "Scout",
    //   type: "internal_link",
    //   summary: "Mobile Frame Zero scouting mech with a sniper rifle.",
    //   tags: ['MFZ', 'lego', 'mech'],
    //   img: "img/sniperscout.png",
    //   link: "https://www.bricklink.com/v3/studio/design.page?idModel=65471"
    // }, {
    //   title: "Pistoleer",
    //   type: "internal_link",
    //   summary: "Mobile Frame with enhanced sensors and dual pistols.",
    //   tags: ['MFZ', 'lego', 'mech'],
    //   img: "img/pistoleer.png",
    //   link: "https://www.bricklink.com/v3/studio/design.page?idModel=66607"
    // }, {
      title: "Dragon Tutorial",
      type: "external_link",
      summary: "A first attempt at making an origami tutorial.",
      tags: ['origami', 'youtube', 'dragon'],
      img: "img/dragon.svg",
      link: "https://youtu.be/kOzWXQF8Z68"
    }, {
      title: "Suffix Trie",
      type: "internal_link",
      summary: "Working through some examples from Ukkonen's lectures on suffix trees.",
      tags: ['algorithms', 'trie', 'D3'],
      link: "https://caseyshields.github.io/suffix"
    }, {
      title: "Transforming A-10",
      type: "external_link", // TODO figure out how to embed youtube
      summary: "A Lego robot that transforms into an A10.",
      tags: ['lego', 'transformer', 'thunderbolt'],
      img: "img/thunderbolt.png",
      link: "https://rebrickable.com/mocs/MOC-25799/deceptibot/transforming-a10-thunderbolt/"
    }, {
      title: "Origami Shadow Boxes",
      type: "external_link",
      summary: "My Etsy store. I sell origami shadow boxes. ",
      tags: ["origami", "art", "store"],
      img: "",
      link: "https://www.etsy.com/shop/CaseyOrigami"
    }, {
      title: "Henderson Origami Club",
      type: "external_link",
      summary: "A meetup club I helped found and teach at",
      tags: ["origami", "teaching", "meetup"],
      img: "",
      link: "https://www.meetup.com/Origami-Meetup-Henderson/"
    }, {
      title: "Rebrickable Gallery",
      type: "external_link",
      summary: "My rebrickable gallery where I share instructions for the models I've made",
      tags: ["Lego", "MOC", "instructions"],
      img: "",
      link: "https://rebrickable.com/users/deceptibot/mocs/"
    }, {
      title: "Orion Star Hunter",
      type: "external_link",
      summary: "A command line program that lets you search star catalogs, extrapolate thier position using Novas, then asynchronously direct sensors on a network at them.",
      tags: ["astronomy", "C", "Novas", "FK6"],
      img: "",
      link: "https://github.com/caseyshields/Orion"
    }
    //<a href="https://studio.bricklink.com/v2/build/user.page?idBuilder=900802"> BrickLink </a>
  ]
};