/** Entry point for the D3ck framework. */
export default function () {

    /** Media types that have corresponding display components */
    let media_types = ['internal_link', 'external_link', 'slide_show'];
    // TODO as we develop more components, flesh out a more informative index...

    /** Standard events generated by UI components */
    let event_types = ['navigate', 'preview', 'filter', 'order'];
    // TODO programmatically retrieve these from components?

    /** the dispatch is how components communicate with the application */
    let dispatch = d3.dispatch( 'navigate', 'preview', 'filter', 'order' );

    return {
        // Card, 
        // Frame,
        media_types,
        event_types,
        dispatch    
    };
}