/** Entry point for the D3ck framework. */

// import Card from './card.js';
// import Frame from './card.js'; // Probably don't want to force the user to download more than they need too...

export default function () {
    /** Media types that have corresponding display coordinates */
    let media_types = ['internal_link', 'external_link', 'slide_show'];
    // TODO as we develop more components, flesh out a more informative index...

    /** Standard events generated by UI components */
    let event_types = ['load_media', 'filter_change', 'order_change'];

    /** the dispatch is how components communicate with teh application */
    let dispatch = d3.dispatch( event_type );

    return {
        // Card, 
        // Frame,
        media_types,
        event_types,
        dispatch    
    };
}